apiVersion: v1
kind: Pod
metadata:
  name: redis-pod-example
  labels:
    app: redis
spec:
  containers:
    - name: redis-container
      image: redis:latest
      env:
        - name: SECRET_NAME # This will be the username from the secret
          valueFrom:
            secretKeyRef:
              name: my-redis-secret # Replace with your actual Secret name
              key: username # Replace with the key in your Secret that holds the username
        - name: SECRET_PASSWORD # This will be the password from the secret
          valueFrom:
            secretKeyRef:
              name: my-redis-secret # Replace with your actual Secret name
              key: password # Replace with the key in your Secret that holds the password
      ports:
        - containerPort: 6379
