apiVersion: v1
kind: Pod
metadata:
  name: multi-container-shared-volume-pod
spec:
  volumes:
    - name: shared-data
      emptyDir: {}
  containers:
    - name: container-1
      image: nginx
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
    - name: container-2
      image: alpine
      command: ["/bin/sh", "-c"]
      args:
        - >
          while true; do                                                    
            echo "Timestamp from container-2: $(date)" > /data/index.html;  
            sleep 5;                                                        
          done
      volumeMounts:
        - name: shared-data
          mountPath: /data
