apiVersion: v1
kind: Pod
metadata:
  name: go-app-pod
  labels:
    app: go-app
    environment: development
spec:
  containers:
    - name: go-app-container
      image: your-go-app-image:latest
      ports:
        - containerPort: 8080
          protocol: TCP
