apiVersion: v1
kind: Pod
metadata:
  name: http-app-pod
  labels:
    app: http-app
spec:
  containers:
    - name: http-app-container
      image: nginx:alpine # Using nginx as a sample HTTP server
      ports:
        - containerPort: 80
          name: http
      livenessProbe:
        httpGet:
          path: / # Nginx serves a default page at /
          port: http
        initialDelaySeconds: 15 # Wait 15 seconds before first probe
        periodSeconds: 20 # Probe every 20 seconds
        timeoutSeconds: 1
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /
          port: http
        initialDelaySeconds: 5 # Wait 5 seconds before first probe
        periodSeconds: 10 # Probe every 10 seconds
        timeoutSeconds: 1
        failureThreshold: 3
      resources:
        requests: # Minimum resources guaranteed to the container
          memory: "64Mi" # 64 Megabytes
          cpu: "0.25" # 0.25 CPU cores (250m)
        limits: # Maximum resources the container can consume
          memory: "128Mi" # 128 Megabytes
          cpu: "0.5" # 0.5 CPU cores (500m)
